spring:
  datasource:
    url: jdbc:mysql://chatroom-bdd.mysql.database.azure.com:3306/chatroom?useSSL=true
    username: bhfr4
    password: RaphHugFabBru4-
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.SQLServer2012Dialect

server:
  port: 8080


